### ISSUE TITLE
powerpc-accton_as4600_54t-r0 hardware identification

### ISSUE THREAD

**Issue by bethomasw** [opennetworklinux/ONL#96]
I have 2 Edge-core AS4600's in my test-lab, the installation of ONL (I took the binaries/installer from the website) fails due to hw-platform detection:

ONIE:/ # onie-nos-install http://172.22.1.209/latest.installer  
Stopping: discover... done.  
Info: Fetching http://172.22.1.209/latest.installer ...  
Connecting to 172.22.1.209 (172.22.1.209:80)  
installer            100% |*******************************|   202M  0:00:00 ETA  
ONIE: Executing installer: http://172.22.1.209/latest.installer  
Open Network Installer running under ONIE.  
Installer Version: Open Network Linux 06c9b88 
(powerpc.all,2015.04.08.12.34,06c9b88a62893397a1539de3fb935e93fe7b7f83)  
Detected platform: powerpc-accton-as4600-54t-r0  
Installing in standalone mode.  
Unpacking Open Network Linux installer files...  
........................(unpacking ;) )..............................

This installer does not support the powerpc-accton-as4600-54t-r0 
platform.  
Available platforms are:  
powerpc-accton-as5700-96x-r0  
powerpc-accton-as5710-54x-r0  
powerpc-accton-as6700-32x-r0  
powerpc-accton-as6700-32x-r1  
powerpc-as4600-54t  
powerpc-as5600-52x  
powerpc-as5610-52x  
powerpc-as5710-54x-r0a  
powerpc-as5710-54x-r0b  
powerpc-as6700-32x-r0  
powerpc-dni-7448-r0  
powerpc-quanta-lb9-r0  
powerpc-quanta-lb9a-r0  
powerpc-quanta-ly2-r0  
Installation cannot continue.  
Install failed.    

The /etc/machine.conf from ONIE:
onie_version=2014.08.00.10
onie_vendor_id=259
onie_platform=powerpc-accton_as4600_54t-r0
onie_machine=accton_as4600_54t
onie_machine_rev=0
onie_arch=powerpc
onie_config_version=0
onie_build_date="2014-10-23T14:49+0800"
onie_partition_type=
onie_kernel_version=3.2.35

**Comment by capveg** [comment]
Thanks for the report.  The interesting thing is your AS4600 reports itself as a different machine than the ones we have in the lab.  Note that your's is a "powerpc-accton_as4600_54t-r0" and our's is a "powerpc-as4600_54t".  Let me do some digging here and get back to you.  Just to give you something to try (it probably won't work :-/) in the mean time, you can try manually setting your ONIE /etc/machine.conf to match mine and then doing the install.  Things will break once you reboot, but then you will have your NOS installed.

[from our lab]
** Installer Mode Enabled **
ONIE:/ # /etc/init.d/discover.sh stop
ONIE:/ # cat /etc/machine.conf 
onie_version=1.6.1
onie_vendor_id=259
onie_platform=powerpc-as4600_54t
onie_machine=as4600_54t
onie_machine_rev=0
onie_arch=powerpc

**Comment by bethomasw** [comment]
I think I have found the cause:
http://www.edge-core.com/temp/ec_download/1490/AS4600-54T_v2014.08.00.10_ReleaseNotes.pdf

Ver. 2014.08.00.05, 2014/09/02
Changed to use the standard naming in 
/etc/machine.conf:
onie_platform=powerpc-accton_as4600_54t-r0
onie_machine=accton_as4600_54t

**Comment by jnealtowns** [comment]
All,

The original platform identifiers for the AS4600 and AS5610 were
powerpc-as4600-54t-r0 and powerpc-as5610-52x-r0, respectively. These did
not conform to the ONIE platform specification and were later changed to
the current canonical identifiers (powerpc-accton-as4600-54t-r0,
powerpc-accton-as5610-52x-r0).

Its just an oversight that the new platform-config packages for these
identifiers were not ported after the conversion. We have both versions in
our lab.

We will add the platform packages to recognize the current platform
identifiers for those two platforms. Support for the original,
preproduction identifiers will also be removed to avoid confusion.

Jeff

**Comment by samrussell** [comment]
I've run into the same issue and the installer has not died but has also left me with an unbootable switch

export installer_platform=powerpc-as4600-54t

I'll have a play and try get it running properly

**Comment by samrussell** [comment]
Looks like there's a bunch of stuff hardcoded in the source so I'll wait for an official patch :)

**Comment by capveg** [comment]
I have a branch going to fix this : https://github.com/capveg/ONL/tree/platform-as4600

I'm doing a clean build now and should be able to post it tomorrow (PST).  Thanks for the interest.

**Comment by samrussell** [comment]
Awesome! I'm in NZT so it is Friday evening already, I can try it in about
60 hours (Monday NZT)

**Comment by samrussell** [comment]
Build just finished so I tried it out - works correctly, orc doesn't start
up but onlpdump seems pretty happy

root@onl-powerpc:~# orc
LOG:        load_driver.c:89  :: Found driver at:
/usr/share/orc/drivers/orc_brcm.so
orc> 05-08 16:54:55.348463 [onlp_platform_defaults] The default
implementation of onlp_sysi_platform_get() has been called.
05-08 16:54:55.348695 [onlp_platform_defaults] This can happen for the
following reasons, all fatal:
05-08 16:54:55.348767 [onlp_platform_defaults] * The ONLP build
configuration is incorrect.
05-08 16:54:55.348834 [onlp_platform_defaults] * The ONLP platform library
for this platform does not contain the onlp_sysi_platform_get() symbol.
05-08 16:54:55.348935 [onlp_platform_defaults] * The ONLP platform shared
libraries are not setup properly before we executed.
05-08 16:54:55.349010 [onlp_platform_defaults] * The platform cannot
continue until this issue is resolved.
Aborted
root@onl-powerpc:~# onlpdump
   System Information = {
       Product Name: 4600-54T-O-AC-B
       Part Number: [removed]
       Serial Number: [removed]
       MAC: [removed]
       MAC Range: [removed]
       Manufacturer: Accton
       Manufacture Date: 01/29/2015 22:32:52
       Vendor: Edgecore
       Platform Name: powerpc-accton_as4600_54t-r0
       Device Version: (null)
       Label Revision: R01E
       Country Code: TW
       Diag Version: 0.0.0.15
       Service Tag: (null)
       ONIE Version: 2014.08.00.10
       CRC: 0x47e387c7
   }
   thermal @ 1 = {
       Description: Chassis Thermal Sensor 1 (Nearby FAN 2)
       Status: 0x00000001 [ PRESENT ]
       Caps:   0x00000001 [ GET_TEMPERATURE ]
       Temperature: 23000
   }
   thermal @ 2 = {
       Description: Chassis Thermal Sensor 2 (CPU)
       Status: 0x00000001 [ PRESENT ]
       Caps:   0x00000001 [ GET_TEMPERATURE ]
       Temperature: 36750
   }
   thermal @ 3 = {
       Description: Chassis Thermal Sensor 3 (First BCM PHY(54280) chip)
       Status: 0x00000001 [ PRESENT ]
       Caps:   0x00000001 [ GET_TEMPERATURE ]
       Temperature: 84000
   }
   thermal @ 4 = {
       Description: Chassis Thermal Sensor 4 (Nearby BCM MAC(56540) chip)
       Status: 0x00000001 [ PRESENT ]
       Caps:   0x00000001 [ GET_TEMPERATURE ]
       Temperature: 25000
   }
   psu @ 1 = {
       Description: PSU-1
       Model:  NULL
       SN:     NULL
       Status: 0x00000005 [ PRESENT,UNPLUGGED ]
       Caps:   0x00000000
       Vin:    0
       Vout:   0
       Iin:    0
       Iout:   0
       Pin:    0
       Pout:   0
   }
   psu @ 2 = {
       Description: PSU-2
       Model:  R12-300P1A
       SN:     NULL
       Status: 0x00000001 [ PRESENT ]
       Caps:   0x00000151 [ AC,VOUT,IOUT,POUT ]
       Vin:    0
       Vout:   12031
       Iin:    0
       Iout:   5273
       Pin:    0
       Pout:   63625
       fan @ 4 = {
           Description: PSU-2 Fan 1
           Status: 0x00000005 [ PRESENT,B2F ]
           Caps:   0x00000009 [ B2F,SET_PERCENTAGE ]
           RPM:    10976
           Per:    0
           Model:  NULL
           SN:     NULL
       }
       thermal @ 6 = {
           Description: PSU-2 Thermal Sensor 1
           Status: 0x00000001 [ PRESENT ]
           Caps:   0x00000001 [ GET_TEMPERATURE ]
           Temperature: 32250
       }
   }
   fan @ 1 = {
       Description: Chassis Fan 1
       Status: 0x00000005 [ PRESENT,B2F ]
       Caps:   0x0000000a [ F2B,SET_PERCENTAGE ]
       RPM:    0
       Per:    0
       Model:  NULL
       SN:     NULL
   }
   fan @ 2 = {
       Description: Chassis Fan 2
       Status: 0x00000005 [ PRESENT,B2F ]
       Caps:   0x0000000a [ F2B,SET_PERCENTAGE ]
       RPM:    0
       Per:    0
       Model:  NULL
       SN:     NULL
   }
   led @ 1 = {
       Description: Chassis LED 1 (DIAG LED)
       Status: 0x00000001 [ PRESENT ]
       Caps:   0x00011001 [ ON_OFF,ORANGE,GREEN ]
       Mode: OFF
   }
   led @ 2 = {
       Description: Chassis LED 2 (PSU1 LED)
       Status: 0x00000001 [ PRESENT ]
       Caps:   0x00011001 [ ON_OFF,ORANGE,GREEN ]
       Mode: ORANGE
   }
   led @ 3 = {
       Description: Chassis LED 3 (PSU2 LED)
       Status: 0x00000001 [ PRESENT ]
       Caps:   0x00011001 [ ON_OFF,ORANGE,GREEN ]
       Mode: GREEN
   }
   led @ 4 = {
       Description: Chassis LED 4 (FAN1 LED)
       Status: 0x00000001 [ PRESENT ]
       Caps:   0x00011001 [ ON_OFF,ORANGE,GREEN ]
       Mode: GREEN
   }
   led @ 5 = {
       Description: Chassis LED 5 (FAN2 LED)
       Status: 0x00000001 [ PRESENT ]
       Caps:   0x00011001 [ ON_OFF,ORANGE,GREEN ]
       Mode: GREEN
   }
   led @ 6 = {
       Description: Chassis LED 6 (MODULE1 LED)
       Status: 0x00000001 [ PRESENT ]
       Caps:   0x00011001 [ ON_OFF,ORANGE,GREEN ]
       Mode: OFF
   }
   led @ 7 = {
       Description: Chassis LED 7 (MODULE2 LED)
       Status: 0x00000001 [ PRESENT ]
       Caps:   0x00011001 [ ON_OFF,ORANGE,GREEN ]
       Mode: OFF
   }

SFPs:
  Presence Bitmap: None
  RX_LOS Bitmap: 48 49 50 51

Port 48: Missing.
Port 49: Missing.
Port 50: Missing.
Port 51: Missing.

**Comment by capveg** [comment]
This is fixed in Pull Request https://github.com/opennetworklinux/ONL/pull/100 and should be merged shortly.

**Comment by samrussell** [comment]
Confirming that I've built from HEAD this morning and it all works on AS4600 (including onlp which was still broken last week but is working now)

**Comment by capveg** [comment]
Great -- thanks!  Yes, there was an intermediary issue with ONLP but I
resolved that - glad to see it's working.


- Rob
.
